{
    "name": "Requisition",
    "category": "purchase",
    "summary": "Manage purchase requisitions and budgets",
    "author": "ewarbot",
    "license": "AGPL-3",
    "version": "18.0.1.0.0",
    "depends": ["purchase", "stock", "date_range"],
    "data": [
        "security/requisition_security.xml",
        "security/ir.model.access.csv",
        "data/purchase_type_data.xml",
        "views/res_company_views.xml",
        "views/purchase_views.xml",
        "views/requisition_budgeting_views.xml",
        "views/purchase_type_views.xml",
        "views/requisition_template_views.xml",
        "views/requisition_line_views.xml",
        "views/requisition_views.xml",
        "views/menu_views.xml",
        "report/paper_format.xml",
        "report/report_requisition.xml",
    ],
    "application": True,
    "auto_install": False,
}
